### ISSUE TITLE
Not all menu options available in menu with QGIS v3.30.1

### ISSUE THREAD

**Issue by NightFalcon650** [NationalSecurityAgency/qgis-mgrs-plugin#2]
I've installed the LatLon Tools restarted QGIS and installed the MGRS plugin. Also restarted after installing the MGRS plugin.
I got no errors, but in the processing toolbar i only got one option the MGRS Grid zone designator. But i can't make the rasters in it.

![image](https://user-images.githubusercontent.com/7109209/234788564-ada7ce1c-5437-436b-8f1c-899c4edb1dbf.png)

What is the problem and how can i get the MGRS plugin to work?

**Comment by hamiltoncj** [comment]
The MGRS tool has 3 tools. Zoom to an MGRS coordinate, copy an MGRS coordinate by clicking on the map, and the  processing algorithm to generate the overall MGRS grid. The first two tools are interactive and are not in the Processing toolbox. Go to Plugins->MGRS and you will see all the tools there.

**Comment by NightFalcon650** [comment]
> The MGRS tool has 3 tools. Zoom to an MGRS coordinate, copy an MGRS coordinate by clicking on the map, and the processing algorithm to generate the overall MGRS grid. The first two tools are interactive and are not in the Processing toolbox. Go to Plugins->MGRS and you will see all the tools there.

Thanks for the quick reaction. In that case the plugin works al do then the next question pops up in the video about the plugin
[https://www.youtube.com/watch?v=qlOx_E-odg8&t=885s](url) on 12min35sec you see there are more functions for creating also the 100x100km and 1x1km. Where are they, why are they taken out and how to get them back or create them?

**Comment by hamiltoncj** [comment]
MGRS Tools only implements the first level MGRS grid. This video is using a geopackage file that contains the more detailed grids. It looks like you can download it here.

https://plugins.qgis.org/geopackages/7/

I never had the time to create a more complete algorithmic MGRS grid and perhaps just having the MGRS grid data is sufficient.

**Comment by hamiltoncj** [comment]
I believe that these questions have been answered so I am closing the ticket. Please open another ticket if you have any further questions or problems.
